interface GeminiRequest {
  prompt: string;
  temperature?: number;
  maxOutputTokens?: number;
}

interface GeminiResponse {
  candidates: {
    content: {
      parts: { text: string }[];
    };
  }[];
}

export class GeminiClient {
  private apiKey: string;
  private apiUrl: string;

  constructor() {
    const apiKey = import.meta.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured");
    }
    this.apiKey = apiKey;
    this.apiUrl = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent";
  }

  /**
   * Generate content using Gemini API
   * @param request - The generation request parameters
   * @returns The generated text content
   * @throws {GeminiApiError} If the API request fails
   * @throws {ServiceUnavailableError} If the service is unavailable
   */
  async generate(request: GeminiRequest): Promise<string> {
    const { prompt, temperature = 0.7, maxOutputTokens = 2048 } = request;

    try {
      const response = await fetch(this.apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": this.apiKey,
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }],
            },
          ],
          generationConfig: {
            temperature,
            maxOutputTokens,
          },
        }),
        signal: AbortSignal.timeout(30000), // 30 second timeout
      });

      if (!response.ok) {
        if (response.status === 503) {
          throw new ServiceUnavailableError("Gemini API is currently unavailable. Please try again later.");
        }
        throw new GeminiApiError(`Gemini API request failed: ${response.status} ${response.statusText}`);
      }

      const data: GeminiResponse = await response.json();

      if (!data.candidates || data.candidates.length === 0) {
        throw new GeminiApiError("No content generated by Gemini API");
      }

      const text = data.candidates[0]?.content?.parts[0]?.text;
      if (!text) {
        throw new GeminiApiError("Invalid response format from Gemini API");
      }

      return text;
    } catch (error) {
      if (error instanceof ServiceUnavailableError || error instanceof GeminiApiError) {
        throw error;
      }
      if (error instanceof Error && error.name === "TimeoutError") {
        throw new GeminiApiError("Gemini API request timed out after 30 seconds");
      }
      throw new GeminiApiError(
        `Failed to communicate with Gemini API: ${error instanceof Error ? error.message : "Unknown error"}`
      );
    }
  }
}

export class GeminiApiError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GeminiApiError";
  }
}

export class ServiceUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ServiceUnavailableError";
  }
}
